import { ArrowLeft, Lightbulb, MessageSquarePlus, Plus, Send } from "lucide-react";
import { useEffect, useState } from "react";
import type { DesktopWorkspace, ProjectIdea, ProjectIdeaDiscussion } from "../contracts/desktop";
import { desktopClient } from "../services/desktop-client";

export function ProjectIdeas({ onReturn, workspace }: { onReturn: () => void; workspace: DesktopWorkspace }) {
  const [ideas, setIdeas] = useState<ProjectIdea[]>([]);
  const [selected, setSelected] = useState<ProjectIdea>();
  const [creating, setCreating] = useState(false);
  async function load() { setIdeas(await desktopClient.listDesktopProjectIdeas(workspace.path)); }
  useEffect(() => { void load(); }, [workspace.path]);
  if (selected || creating) return <IdeaEditor idea={selected} onBack={() => { setCreating(false); setSelected(undefined); void load(); }} workspace={workspace} />;
  return <section className="project-ideas project-ideas-page" aria-label="Project ideas">
    <button className="project-details-back" onClick={onReturn} type="button"><ArrowLeft size={16} /> Return to project</button>
    <header className="project-ideas-page-header"><div><p>Project ideas</p><h1>{workspace.projectName?.trim() || workspace.name}</h1><span>Explore a direction before it becomes a project task.</span></div><button className="project-ideas-primary" onClick={() => setCreating(true)} type="button"><Plus size={15} /> New idea</button></header>
    {ideas.length ? <ul className="project-ideas-list">{ideas.map((idea) => <li key={idea.id}><button onClick={() => setSelected(idea)} type="button"><Lightbulb size={17} /><span><strong>{idea.title}</strong><small>{idea.context || "No context recorded yet"}</small></span><em>{idea.discussionCount} discussions</em><ArrowLeft className="project-ideas-forward" size={16} /></button></li>)}</ul> : <section className="project-ideas-empty"><Lightbulb size={19} /><strong>No ideas yet</strong><p>Capture a project direction, discuss it, and only then make it a task.</p><button className="project-ideas-primary" onClick={() => setCreating(true)} type="button"><Plus size={15} /> Add first idea</button></section>}
  </section>;
}

function IdeaEditor({ idea, onBack, workspace }: { idea: ProjectIdea | undefined; onBack: () => void; workspace: DesktopWorkspace }) {
  const [title, setTitle] = useState(idea?.title ?? ""); const [context, setContext] = useState(idea?.context ?? ""); const [discussions, setDiscussions] = useState<ProjectIdeaDiscussion[]>([]); const [entry, setEntry] = useState(""); const [current, setCurrent] = useState(idea); const [error, setError] = useState<string>(); const [saving, setSaving] = useState(false);
  useEffect(() => { if (idea) void desktopClient.listDesktopProjectIdeaDiscussions(workspace.path, idea.id).then(setDiscussions); }, [idea, workspace.path]);
  async function saveIdea() { setSaving(true); setError(undefined); try { const saved = await desktopClient.saveDesktopProjectIdea(workspace.path, title, context, ""); setCurrent(saved); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setSaving(false); } }
  async function addDiscussion() { if (!current) return; setSaving(true); setError(undefined); try { const saved = await desktopClient.saveDesktopProjectIdeaDiscussion(workspace.path, current.id, entry); setDiscussions([...discussions, saved]); setEntry(""); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setSaving(false); } }
  async function convert() { if (!current) return; setSaving(true); try { const saved = await desktopClient.convertDesktopProjectIdea(workspace.path, current.id); setCurrent(saved); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setSaving(false); } }
  return <section className="project-ideas project-ideas-page project-idea-editor"><button className="project-details-back" onClick={onBack} type="button"><ArrowLeft size={16} /> All ideas</button><header className="project-ideas-page-header"><div><p>{current ? "Idea discussion" : "New idea"}</p><h1>{current?.title || "Shape an idea"}</h1><span>Keep this direction separate from execution until it is ready.</span></div>{current && !current.convertedTaskId ? <button className="project-ideas-primary" disabled={saving} onClick={() => void convert()} type="button"><Send size={15} /> Convert to task</button> : current?.convertedTaskId ? <span className="project-idea-task">Task #{current.convertedTaskId}</span> : null}</header>{!current ? <form className="project-idea-form" onSubmit={(event) => { event.preventDefault(); void saveIdea(); }}><label>Idea title<input autoFocus maxLength={180} onChange={(event) => setTitle(event.target.value)} placeholder="What should this project explore?" required value={title} /></label><label>Context<textarea maxLength={4000} onChange={(event) => setContext(event.target.value)} placeholder="Outcome, problem, or opportunity" rows={5} value={context} /></label><footer><button onClick={onBack} type="button">Cancel</button><button className="project-ideas-primary" disabled={saving} type="submit">Save idea</button></footer></form> : <><section className="project-idea-context"><strong>Context</strong><p>{current.context || "No context recorded."}</p></section><section className="project-discussions"><header><MessageSquarePlus size={16} /><strong>Discussion</strong><span>{discussions.length} entries</span></header>{discussions.length ? <ol>{discussions.map((item) => <li key={item.id}><p>{item.content}</p><small>{item.createdAt}</small></li>)}</ol> : <p className="project-ideas-empty">No discussion entries yet.</p>}<form onSubmit={(event) => { event.preventDefault(); void addDiscussion(); }}><textarea maxLength={4000} onChange={(event) => setEntry(event.target.value)} placeholder="Add a discussion note, question, decision, or next step" required rows={3} value={entry} /><button className="project-ideas-primary" disabled={saving} type="submit">Add discussion</button></form></section></>}{error ? <p className="project-idea-error" role="alert">{error}</p> : null}</section>;
}
