import { Button } from "@neot/ui/components/button";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BookOpenCheckIcon, HistoryIcon, MessageSquareTextIcon, ShieldCheckIcon } from "lucide-react";
import { getHoneyDashboard, reviewHoneyKnowledge } from "./honey.services";
import type { HoneyKnowledge } from "./honey.types";

export function HoneyDashboard() {
  const queryClient = useQueryClient();
  const dashboard = useQuery({ queryKey: ["honey", "dashboard"], queryFn: getHoneyDashboard });
  const review = useMutation({ mutationFn: ({ id, status }: { id: string; status: "approved" | "rejected" | "reverted" }) => reviewHoneyKnowledge(id, status), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["honey", "dashboard"] }) });
  const data = dashboard.data;
  return <div className="mx-auto flex w-full max-w-5xl flex-1 flex-col gap-6 overflow-y-auto px-5 py-6"><div><h2 className="text-xl font-semibold">Honey knowledge control</h2><p className="pt-1 text-sm text-muted-foreground">Review every learning proposal before Honey can use it.</p></div><div className="grid gap-4 sm:grid-cols-3"><Metric icon={MessageSquareTextIcon} label="Conversations" value={data?.conversations ?? 0}/><Metric icon={BookOpenCheckIcon} label="Approved knowledge" value={data?.reports.approved ?? 0}/><Metric icon={HistoryIcon} label="Awaiting review" value={data?.reports.pending ?? 0}/></div><section><h3 className="font-semibold">Approved skills and business concepts</h3><div className="flex flex-wrap gap-2 pt-3">{data?.approvedSkills.map((skill) => <span className="rounded-full border border-amber-200 px-3 py-1 text-sm" key={skill}>{skill}</span>)}</div></section><section><div className="flex items-center gap-2"><ShieldCheckIcon className="size-4 text-amber-700"/><h3 className="font-semibold">Skills, concepts, and memory</h3></div><div className="divide-y pt-3">{data?.knowledge.length ? data.knowledge.map((item) => <KnowledgeRow item={item} key={item.id} onReview={(status) => review.mutate({ id: item.id, status })}/>) : <p className="py-8 text-sm text-muted-foreground">No learning suggestions are waiting for review.</p>}</div></section><section><h3 className="font-semibold">Conversation review</h3><div className="divide-y pt-2">{data?.conversationReview.map((item) => <a className="flex items-center justify-between gap-4 py-3 text-sm hover:text-amber-700" href={`/app/neot/honey?thread=${item.id}`} key={item.id}><span className="truncate">{item.title}</span><time className="shrink-0 text-xs text-muted-foreground">{new Date(item.updatedAt).toLocaleDateString()}</time></a>)}</div></section><p className="text-sm text-muted-foreground">Usage report: {data?.reports.unresolved ?? 0} unresolved suggestions. Rejected and reverted versions remain in the audit history.</p></div>;
}
function Metric({ icon: Icon, label, value }: { icon: typeof MessageSquareTextIcon; label: string; value: number }) { return <div className="flex items-center gap-3 rounded-xl bg-muted/40 p-4"><Icon className="size-5 text-amber-700"/><div><strong className="text-xl">{value}</strong><p className="text-sm text-muted-foreground">{label}</p></div></div>; }
function KnowledgeRow({ item, onReview }: { item: HoneyKnowledge; onReview: (status: "approved" | "rejected" | "reverted") => void }) { return <article className="flex flex-col gap-3 py-4 sm:flex-row sm:items-start"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-amber-50 px-2 py-0.5 text-xs font-medium text-amber-800">{item.status}</span><span className="text-xs text-muted-foreground">v{item.version} · {item.kind}</span></div><p className="pt-2 text-sm leading-6">{item.content}</p><p className="pt-1 text-xs text-muted-foreground">Source: {item.source}</p></div><div className="flex shrink-0 gap-2">{item.status === "pending" ? <><Button onClick={() => onReview("rejected")} size="sm" variant="ghost">Reject</Button><Button onClick={() => onReview("approved")} size="sm">Approve</Button></> : null}{item.status === "approved" ? <Button onClick={() => onReview("reverted")} size="sm" variant="outline">Revert</Button> : null}</div></article>; }
